### ISSUE TITLE
Ability to add more services

### ISSUE THREAD

**Issue by jamierocks** [pyupio/statuspage#17]
I have tried adding more labels, so I guess it isn't possible?

// EDIT: I haven't tried manually adding them to the index.html, so maybe that'll work. Just depends on if they stick after updating.

**Comment by jayfk** [comment]
Systems are identified by the label's color. Try setting the color to #171717.

**Comment by jamierocks** [comment]
All my systems have separate colours.

**Comment by jamierocks** [comment]
How can I add more services to an already created statuspage?

**Comment by jamierocks** [comment]
I see what you mean now - thanks ;)
