### ISSUE TITLE
Simpel comment

### ISSUE THREAD

**Issue by seggiovia** [pyupio/statuspage#18]
Hi @jayfk, you had the good idea of using gh to host your status page, but if I need a remote vps or whatever to generate the code and git push, I could directly host http://www.stashboard.org on my vps.

Why dont you take a different approach and write a all-javascript app that parses the issues from, let's say, https://api.github.com/repos/jayfk/statuspage-demo/issues and displays them like you are doing with statuspage?
You would be using gh's issues manager like in your current app, but everything would be hosted on gh.

Hope this helps, thanks.

**Comment by jayfk** [comment]
See #5
