### ISSUE TITLE
Status Page for Dummies !

### ISSUE THREAD

**Issue by leovarmak** [pyupio/statuspage#32]
Hey, I would like to put a status page on my website which is on a shared hosting. It is a linux server. Actually there is no need for a status page but I would like to keep one as to make it more professional. So can I do this on shared hosting server ?

**Comment by jayfk** [comment]
Yeah, you can do that. Your page will be hosted on GitHub, so this has nothing to do with what your are currently using to host your main website.

Take a look at [GitHub Pages](https://pages.github.com/) for more info on that.

**Comment by leovarmak** [comment]
Hey, thanks that helped. When I copy pasted the Installation for Mac it was like 'No file or such directory'
