### ISSUE TITLE
Binary doesn't works on Debian 8

### ISSUE THREAD

**Issue by MrHalfman** [pyupio/statuspage#4]
Hi,

I had to clone the repo and build it on Debian to make it work. The binary given in the Readme seems to be compatible for OSX only.

Regards,
Halfman.

**Comment by jayfk** [comment]
I've pushed a new binary for Linux and updated the readme. 

I'll leave this open because the build/distribution process is not ideal at the moment.

**Comment by jayfk** [comment]
Added new linux binary in f5a46d12cd07f86a8f9baaea0f678f71c5a73482, and added instructions for installation on linux in 581d4fadf5c470c157c4d67c624fefa0692e2f46
