### ISSUE TITLE
Being able to remove isses

### ISSUE THREAD

**Issue by casdr** [pyupio/statuspage#7]
I would like to be able to remove an issue. I've created some test issues, but as you might knw it isn't possible to remove any issues on GitHub itself. Maybe create an extra label called "removed" or "hidden"?

**Comment by jayfk** [comment]
There's currently a bug so this won't work, but the idea was to just remove all labels from the issue.

**Comment by jayfk** [comment]
I've just pushed a new release. This should be possible now:

- Upgrade to the newest release (just download again with curl)
- On all issues you don't want to be displayed, remove all labels 
- run `statuspage update` again
