### ISSUE TITLE
Add organisation support

### ISSUE THREAD

**Issue by wyaeld** [pyupio/statuspage#8]
I tried but it blew up.  It shouldn't take much to be able to create the repo under a specified organisation, rather than under an individual account.

**Comment by ssx** [comment]
+1 - can't use this myself until org support is added.

**Comment by casdr** [comment]
I've done this by creating it in my personal account first and then transferring it to the org.

**Comment by jayfk** [comment]
I've added org support in  https://github.com/pyupio/statuspage/commit/f911e29e8a815de2030b99a008472c449ea7c5fa

You basically just add `--org=your-org` to the create/update command. For more, see: https://github.com/pyupio/statuspage#use-organization-account

**Comment by wyaeld** [comment]
you're a champion @jayfk
