### ISSUE TITLE
Anyone could create a new issue

### ISSUE THREAD

**Issue by Jamesking56** [pyupio/statuspage#9]
Couldn't anyone technically make an issue and publish to your status page... Is there any way to stop this?

**Comment by jayfk** [comment]
The idea was that issues without labels won't be displayed (non-maintainers can't add labels), but there's currently a bug where every issue is used to render the template.

But there's another thing: If someone comments on an issue, his/hers comment will be displayed. I haven't checked it yet, but it should be possible to limit this to maintainers.

**Comment by jayfk** [comment]
Fixed in https://github.com/pyupio/statuspage/commit/bc0661ae686fe3c17abe7a4f7044e2f45707e5d5
